language: node_js
sudo: false

node_js:
  - "0.12"
  - "iojs"
  - "4"
  - "5"
  - "6"
  - "node"

matrix:
  allow_failures:
    - node_js: "node"

before_script:
  - export HARMONY_OPTS=$(node --v8-options | grep --only-matching -- '--harmony_generators')

after_script:
  - npm run coveralls
